# 主菜单
[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"
[[main]]
    identifier = "selfie"
    name = "每日自拍"
    url = "/selfie/"
    weight = 2
    [main.params]
        icon = "home"