# 默认去 content/post 文件夹找文章
mainSections = ["tech", "diary", "life"]
rssFullContent = true
favicon = "img/avatar.png" # 浏览器标签页图标

[sidebar]
    avatar = "img/avatar.png"  # 侧边栏头像，请确保 assets/img/avatar.png 存在

[footer]
    since = 2026

# 首页右侧显示的组件
[widgets]
    homepage = [
        { type = "categories"}
    ]
    page = [{ type = "toc" }] # 文章页目录保留，这个很有用

[comments]
    enabled = false